.TH TRIM 1 "December 21, 2016"
.SH NAME
trim \- Strip lines
.SH SYNOPSIS
.B trim
.RI [ OPTION ]
.SH DESCRIPTION
Acts as a filter: read stdin and print a trimmed version of each lines on stdout.
.TP
.BR \-s ", " \-\-start-line-only
Removes spaces and tabs at the beginning of each lines.
.TP
.BR \-e ", " \-\-end-line-only
Removes spaces and tabs at the end of each lines.
.SH COPYRIGHT
This software is free software and is released under the GNU GPL version 3 or upper <http://gnu.org/licenses/gpl.html>
